version: "3.7"

services:
  api:
    container_name: api
    build: ./Server/BackEndTryitter/BackEndTryitter
    ports:
        - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_CONNECTION_STRING=Server=db;Database=Tryitter;User=SA;Password=Password123;
  db:
    container_name: sql_server_db
    image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
    ports:
        - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
      - MSSQL_PID=Developer